package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	clicmd "github.com/nebari-dev/skillsctl/cli/cmd"
)

func TestRun(t *testing.T) {
	out := t.TempDir()
	if err := run(clicmd.NewRootCmd(), out); err != nil {
		t.Fatalf("run: %v", err)
	}

	wantFiles := []string{
		"skillsctl.md",
		"skillsctl_install.md",
		"skillsctl_publish.md",
		"skillsctl_explore.md",
		"skillsctl_auth.md",
		"skillsctl_config.md",
	}

	for _, name := range wantFiles {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(out, name)
			body, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read %s: %v", path, err)
			}
			content := string(body)

			if !strings.HasPrefix(content, "---\ntitle: ") {
				t.Errorf("%s: missing Hugo frontmatter; first 40 bytes: %q", name, content[:min(len(content), 40)])
			}
			if strings.Contains(content, "Auto generated by spf13/cobra") {
				t.Errorf("%s: DisableAutoGenTag should suppress the auto-gen tag", name)
			}
		})
	}
}
